spring:
  application:
    name: ms-api-gateway

  config:
    import: "vault://"

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  cloud:
    vault:
      uri: ${SPRING_CLOUD_VAULT_URI:http://localhost:8200}
      token: ${SPRING_CLOUD_VAULT_TOKEN:root-token}
      enabled: true
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        default-context: ms-api-gateway
        backend-version: 2

    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true
            maxAge: 3600

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      timeout: 3000ms
      password: ${spring.data.redis.password:}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

jwt:
  issuer: user-service
  access:
    secret: ${jwt.access.secret}

logging:
  level:
    root: INFO
    com.ecommerce.apigateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
